FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install

# Not neccessary for our dev environment as Docker Volume is mapping the project files
# Leaving in as a reference for future Dockerfiles (production, tests, etc.)
COPY . . 

CMD [ "npm", "run", "start" ] 